sonar.projectKey=23suca31-rgb_dietandlifestyle-frontend
sonar.organization=23suca31-rgb
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=coverage/**
sonar.sourceEncoding=UTF-8
